// Textos da execução do treino (pt-BR), num lugar só e prontos para i18n.
export const strings = {
  run: {
    back: "Minimizar",
    finish: "Finalizar",
    elapsed: "Tempo de treino",
    exercise: (n: number, total: number) => `Exercício ${String(n)} de ${String(total)}`,
    previous: "Exercício anterior",
    next: "Próximo exercício",
    set: "Série",
    kg: "kg",
    reps: "reps",
    seconds: "seg",
    meters: "m",
    confirm: (n: number) => `Confirmar série ${String(n)}`,
    undo: (n: number) => `Desfazer série ${String(n)}`,
    planned: "planejado",
    addSet: "Mais uma série",
    howTo: "Como fazer",
    video: "Ver vídeo",
    skip: "Pular exercício",
    skipped: "Pulado",
    unskip: "Voltar a fazer",
    substitute: "Trocar exercício",
    substitutedFrom: (name: string) => `no lugar de ${name}`,
    substituteTitle: "Trocar por",
    substituteHint: "Exercícios do seu programa para o mesmo músculo.",
    substituteHintLibrary: "Exercícios da biblioteca para o mesmo músculo.",
    noSubstitute: "Nenhum outro exercício do programa trabalha esse músculo.",
    close: "Fechar",
    notes: "Recado do personal",
    offline: "Sem conexão: tudo fica salvo e vai depois.",
    finishPendingTitle: "Finalizar com exercícios pendentes?",
    finishPendingMessage: "O que não foi feito fica registrado como pendente.",
    finishPendingBack: "Continuar treinando",
    finishPendingGo: "Finalizar assim",
    discard: "Descartar treino",
    discardTitle: "Descartar este treino?",
    discardMessage: "Nada do que foi registrado hoje vai ficar.",
  },
  rest: {
    title: "Descanso",
    skip: "Pular descanso",
    more: "+30 s",
    next: (name: string) => `Depois: ${name}`,
  },
  timed: {
    work: "Esforço",
    rest: "Descanso",
    round: (n: number, total: number) => `Rodada ${String(n)} de ${String(total)}`,
    minute: (n: number, total: number) => `Minuto ${String(n)} de ${String(total)}`,
    remaining: "Tempo restante",
    rounds: "Rodadas completas",
    start: "Começar",
    pause: "Pausar",
    resume: "Continuar",
    done: "Bloco feito",
    addRound: "Mais uma rodada",
    removeRound: "Menos uma rodada",
  },
  feedback: {
    title: "Como foi\no treino?",
    effort: "Esforço (0 = leve, 10 = máximo)",
    effortValue: (n: number) => `Esforço ${String(n)} de 10`,
    comment: "Comentário para o personal (opcional)",
    pain: "Senti dor",
    painHint: "Seu personal recebe o aviso e ajusta o treino.",
    where: "Onde?",
    intensity: "Intensidade (0 a 10)",
    whichExercise: "Em qual exercício?",
    none: "Nenhum específico",
    save: "Concluir treino",
    regions: {
      neck: "Pescoço",
      shoulder_left: "Ombro esq.",
      shoulder_right: "Ombro dir.",
      elbow_left: "Cotovelo esq.",
      elbow_right: "Cotovelo dir.",
      wrist_left: "Punho esq.",
      wrist_right: "Punho dir.",
      chest: "Peito",
      upper_back: "Costas",
      lower_back: "Lombar",
      hip_left: "Quadril esq.",
      hip_right: "Quadril dir.",
      knee_left: "Joelho esq.",
      knee_right: "Joelho dir.",
      ankle_left: "Tornozelo esq.",
      ankle_right: "Tornozelo dir.",
      other: "Outro lugar",
    },
  },
  summary: {
    title: (name: string) =>
      name.length <= 9 && name.length > 0 ? `Mandou\nbem, ${name}.` : "Mandou\nbem.",
    duration: "duração",
    volume: "volume",
    sets: "séries",
    worked: "Músculos do dia",
    compare: "Comparado à última vez",
    first: "Primeira vez deste treino: na próxima aparece a comparação.",
    up: (kg: string) => `+${kg} kg`,
    down: (kg: string) => `−${kg} kg`,
    same: "igual",
    pending: "Salvo no celular. Vai para o personal quando tiver internet.",
    synced: "Enviado para o personal.",
    done: "Concluir",
  },
  history: {
    title: "Histórico",
    emptyTitle: "Seu primeiro treino aparece aqui",
    emptyText:
      "Cada treino terminado fica salvo com carga e esforço, para você comparar com a vez anterior.",
    pending: "Ainda não enviado",
    partial: "parcial",
    edit: "Corrigir séries",
    save: "Salvar correção",
    back: "Voltar",
    edited: "Correção salva. Vai para o personal assim que possível.",
  },
  start: {
    start: "Começar treino",
    resume: "Retomar treino",
    presencial: "Treino presencial",
    presencialHint: "Você registra as séries pelo aluno.",
  },
} as const;
