import type { ClientAction, LinkStatus } from "../domain/client";

// Textos da feature clients (pt-BR), num lugar só e prontos para i18n.
export const strings = {
  list: {
    title: "Alunos",
    count: (n: number) => (n === 1 ? "1 aluno" : `${String(n)} alunos`),
    filter: "Filtrar alunos",
    filters: {
      all: (n: number) => `Todos ${String(n)}`,
      active: (n: number) => `Ativos ${String(n)}`,
      invites: (n: number) => `Convites ${String(n)}`,
    },
    invite: "Convidar aluno",
    emptyTitle: "Convide seu primeiro aluno",
    emptyText: "Pelo WhatsApp ou QR Code. Assim que ele aceitar, os treinos dele aparecem aqui.",
    emptyFilter: "Ninguém neste filtro.",
    error: "Não conseguimos carregar seus alunos.",
    retry: "Tentar de novo",
    loadMore: "Carregar mais",
    inviteExpires: (date: string) => `Convite vale até ${date}`,
    noInvite: "Convite vencido. Reenvie para gerar um novo.",
    since: (date: string) => `Desde ${date}`,
  },
  status: {
    pending: "Pendente",
    active: "Ativo",
    inactive: "Inativo",
  } satisfies Record<LinkStatus, string>,
  actions: {
    share: "Compartilhar convite",
    resend: "Reenviar convite",
    "cancel-invite": "Cancelar convite",
    inactivate: "Inativar",
    reactivate: "Reativar",
    end: "Encerrar",
  } satisfies Record<ClientAction, string>,
  confirmBack: "Voltar",
  confirm: {
    "cancel-invite": {
      title: "Cancelar convite?",
      message: "O código e o link deixam de funcionar. Você pode reenviar depois.",
    },
    inactivate: {
      title: "Inativar aluno?",
      message: "Ele deixa de contar no limite do plano e não recebe treinos até ser reativado.",
    },
    end: {
      title: "Encerrar vínculo?",
      message: "O aluno sai da sua lista. O histórico dele continua guardado na conta dele.",
    },
  },
  form: {
    title: "Novo\naluno",
    subtitle: "Só o básico. O resto ele completa ao aceitar.",
    name: "Nome",
    phone: "WhatsApp com DDD",
    phonePlaceholder: "(11) 98765-4321",
    email: "E-mail (opcional)",
    goal: "Objetivo",
    goals: ["Hipertrofia", "Emagrecer", "Condicionamento", "Saúde"],
    submit: "Criar convite",
    close: "Fechar",
    nameInvalid: "Informe um nome entre 2 e 200 caracteres.",
    emailInvalid: "Confira o e-mail.",
    phoneInvalid: "Confira o WhatsApp, com DDD.",
    goalTooLong: "O objetivo pode ter até 500 caracteres.",
  },
  share: {
    title: "Convite\npronto",
    code: "Código do convite",
    expires: (date: string) => `Vale até ${date} · uso único`,
    qrLabel: "QR Code do convite",
    qrHint: "Na academia? O aluno aponta a câmera para o QR Code.",
    whatsapp: "Enviar no WhatsApp",
    shareOther: "Compartilhar",
    close: "Fechar",
    whatsappFailed: "Não foi possível abrir o WhatsApp. Use o botão Compartilhar.",
    invalid: "Convite inválido. Volte para a lista de alunos.",
  },
} as const;
