-- =====================================================================
-- V17 — Biblioteca base de exercícios (organization_id nulo = todos veem)
--
--  * Músculos com os mesmos códigos do mapa muscular do app
--    (chest, delts, traps, abs, lats, biceps, triceps, forearms, quads,
--    adductors, abductors, calves, lowerback, glutes, hamstrings).
--  * Instruções curtas e próprias do MoveUp (sem texto de terceiros).
--  * Equipamento em português, como o personal fala.
--  * O personal cria os próprios exercícios na organização dele; os da
--    base não são editáveis pelo app.
-- =====================================================================

alter table exercise
  add constraint exercise_primary_muscle_code check (primary_muscle is null or primary_muscle in
    ('chest','delts','traps','abs','lats','biceps','triceps','forearms','quads',
     'adductors','abductors','calves','lowerback','glutes','hamstrings')),
  add constraint exercise_secondary_muscles_code check (secondary_muscles <@ array
    ['chest','delts','traps','abs','lats','biceps','triceps','forearms','quads',
     'adductors','abductors','calves','lowerback','glutes','hamstrings']::text[]);

create index exercise_org_idx on exercise (organization_id) where archived_at is null;

insert into exercise (organization_id, name, modality, tracking_type, primary_muscle,
                      secondary_muscles, equipment, is_unilateral, instructions)
values
-- Peito
(null, 'Supino reto com barra', 'strength', 'reps_load', 'chest', '{triceps,delts}', 'barra', false,
 'Deitado no banco, pés firmes no chão. Desça a barra até o meio do peito com os cotovelos a uns 45° do tronco e empurre de volta até estender os braços.'),
(null, 'Supino reto com halteres', 'strength', 'reps_load', 'chest', '{triceps,delts}', 'halteres', false,
 'Deitado no banco, halteres na linha do peito. Empurre para cima aproximando os halteres no alto e desça devagar até sentir o alongamento do peito.'),
(null, 'Supino inclinado com barra', 'strength', 'reps_load', 'chest', '{delts,triceps}', 'barra', false,
 'Banco a 30–45°. Desça a barra até a parte de cima do peito e empurre de volta sem tirar as costas do banco.'),
(null, 'Supino inclinado com halteres', 'strength', 'reps_load', 'chest', '{delts,triceps}', 'halteres', false,
 'Banco a 30–45°. Empurre os halteres para cima e desça controlando até a linha do peito.'),
(null, 'Supino declinado com barra', 'strength', 'reps_load', 'chest', '{triceps}', 'barra', false,
 'Banco declinado com as pernas presas. Desça a barra até a parte de baixo do peito e empurre de volta.'),
(null, 'Supino na máquina', 'strength', 'reps_load', 'chest', '{triceps,delts}', 'máquina', false,
 'Ajuste o banco para a pegada ficar na linha do peito. Empurre até estender os braços e volte devagar.'),
(null, 'Crucifixo com halteres', 'strength', 'reps_load', 'chest', '{delts}', 'halteres', false,
 'Deitado, braços quase estendidos e cotovelos levemente dobrados. Abra até sentir o peito alongar e feche desenhando um arco.'),
(null, 'Crucifixo inclinado com halteres', 'strength', 'reps_load', 'chest', '{delts}', 'halteres', false,
 'Banco a 30°. Abra os braços em arco com os cotovelos levemente dobrados e feche no alto.'),
(null, 'Crucifixo na máquina (voador)', 'strength', 'reps_load', 'chest', '{delts}', 'máquina', false,
 'Costas apoiadas, cotovelos na altura dos ombros. Feche os braços à frente e volte devagar.'),
(null, 'Crossover na polia', 'strength', 'reps_load', 'chest', '{delts}', 'polia', false,
 'Um passo à frente, tronco levemente inclinado. Traga as mãos para a frente e para baixo até se encontrarem e volte controlando.'),
(null, 'Flexão de braço', 'strength', 'reps_only', 'chest', '{triceps,delts,abs}', 'peso do corpo', false,
 'Mãos um pouco além da largura dos ombros, corpo reto da cabeça aos pés. Desça até o peito quase tocar o chão e empurre de volta.'),
(null, 'Mergulho nas paralelas', 'strength', 'reps_only', 'chest', '{triceps,delts}', 'paralelas', false,
 'Corpo levemente inclinado à frente. Desça até os cotovelos chegarem a 90° e empurre de volta.'),
-- Costas
(null, 'Puxada frontal na polia', 'strength', 'reps_load', 'lats', '{biceps}', 'polia', false,
 'Pegada aberta, peito alto. Puxe a barra até a parte de cima do peito levando os cotovelos para baixo e volte devagar.'),
(null, 'Puxada com triângulo', 'strength', 'reps_load', 'lats', '{biceps}', 'polia', false,
 'Pegada neutra fechada. Puxe até o peito sem jogar o tronco para trás e volte estendendo os braços.'),
(null, 'Barra fixa', 'strength', 'reps_only', 'lats', '{biceps,forearms}', 'barra fixa', false,
 'Pendurado com os braços estendidos. Puxe até o queixo passar a barra e desça controlando.'),
(null, 'Remada curvada com barra', 'strength', 'reps_load', 'lats', '{traps,biceps,lowerback}', 'barra', false,
 'Tronco inclinado à frente com a coluna neutra. Puxe a barra até o umbigo e desça sem arredondar as costas.'),
(null, 'Remada unilateral com halter (serrote)', 'strength', 'reps_load', 'lats', '{traps,biceps}', 'halteres', true,
 'Joelho e mão apoiados no banco. Puxe o halter até a cintura levando o cotovelo para trás e desça devagar.'),
(null, 'Remada baixa na polia', 'strength', 'reps_load', 'lats', '{traps,biceps}', 'polia', false,
 'Sentado, coluna neutra. Puxe o triângulo até o abdômen juntando as escápulas e volte estendendo os braços.'),
(null, 'Remada na máquina', 'strength', 'reps_load', 'lats', '{traps,biceps}', 'máquina', false,
 'Peito apoiado. Puxe as alças levando os cotovelos para trás e volte devagar.'),
(null, 'Pulldown com braços estendidos', 'strength', 'reps_load', 'lats', '{triceps}', 'polia', false,
 'Em pé, braços quase estendidos. Leve a barra da altura do rosto até as coxas em arco e volte.'),
(null, 'Levantamento terra', 'strength', 'reps_load', 'lowerback', '{glutes,hamstrings,traps,quads}', 'barra', false,
 'Barra perto da canela, coluna neutra. Levante estendendo quadril e joelhos juntos e desça a barra rente às pernas.'),
(null, 'Hiperextensão lombar', 'strength', 'reps_only', 'lowerback', '{glutes,hamstrings}', 'banco romano', false,
 'Quadril apoiado no banco. Desça o tronco com a coluna neutra e suba até alinhar com as pernas, sem passar disso.'),
(null, 'Encolhimento com halteres', 'strength', 'reps_load', 'traps', '{}', 'halteres', false,
 'Em pé, braços estendidos. Suba os ombros em direção às orelhas, segure um instante e desça.'),
-- Ombros
(null, 'Desenvolvimento com halteres', 'strength', 'reps_load', 'delts', '{triceps}', 'halteres', false,
 'Sentado, halteres na altura das orelhas. Empurre para cima sem bater um no outro e desça até a linha do queixo.'),
(null, 'Desenvolvimento com barra', 'strength', 'reps_load', 'delts', '{triceps,traps}', 'barra', false,
 'Em pé ou sentado, barra na frente do pescoço. Empurre para cima e desça até a altura do queixo.'),
(null, 'Desenvolvimento na máquina', 'strength', 'reps_load', 'delts', '{triceps}', 'máquina', false,
 'Ajuste o banco para as alças ficarem na altura dos ombros. Empurre para cima e volte devagar.'),
(null, 'Elevação lateral com halteres', 'strength', 'reps_load', 'delts', '{traps}', 'halteres', false,
 'Em pé, cotovelos levemente dobrados. Eleve os braços para os lados até a altura dos ombros e desça devagar.'),
(null, 'Elevação lateral na polia', 'strength', 'reps_load', 'delts', '{}', 'polia', true,
 'De lado para a polia. Eleve o braço até a altura do ombro e desça controlando.'),
(null, 'Elevação frontal com halteres', 'strength', 'reps_load', 'delts', '{chest}', 'halteres', false,
 'Em pé, braços à frente das coxas. Eleve até a altura dos ombros e desça devagar.'),
(null, 'Crucifixo invertido na máquina', 'strength', 'reps_load', 'delts', '{traps}', 'máquina', false,
 'Peito apoiado no voador, de frente. Abra os braços para trás na altura dos ombros e volte.'),
(null, 'Face pull na polia', 'strength', 'reps_load', 'delts', '{traps}', 'polia', false,
 'Corda na altura do rosto. Puxe em direção à testa abrindo os cotovelos e volte devagar.'),
-- Braços
(null, 'Rosca direta com barra', 'strength', 'reps_load', 'biceps', '{forearms}', 'barra', false,
 'Em pé, cotovelos colados ao corpo. Suba a barra dobrando os cotovelos e desça até estender sem balançar o tronco.'),
(null, 'Rosca alternada com halteres', 'strength', 'reps_load', 'biceps', '{forearms}', 'halteres', true,
 'Em pé, palmas para dentro. Suba um halter girando a palma para cima e desça; alterne os braços.'),
(null, 'Rosca martelo', 'strength', 'reps_load', 'biceps', '{forearms}', 'halteres', false,
 'Palmas viradas uma para a outra o tempo todo. Suba os halteres dobrando os cotovelos e desça devagar.'),
(null, 'Rosca Scott', 'strength', 'reps_load', 'biceps', '{forearms}', 'banco Scott', false,
 'Braços apoiados no banco. Suba a barra e desça até quase estender, sem tirar os braços do apoio.'),
(null, 'Rosca na polia', 'strength', 'reps_load', 'biceps', '{forearms}', 'polia', false,
 'De frente para a polia baixa. Suba a barra dobrando os cotovelos e volte devagar.'),
(null, 'Tríceps na polia (barra)', 'strength', 'reps_load', 'triceps', '{}', 'polia', false,
 'Cotovelos colados ao corpo. Empurre a barra para baixo até estender os braços e volte até 90°.'),
(null, 'Tríceps na corda', 'strength', 'reps_load', 'triceps', '{}', 'polia', false,
 'Cotovelos colados ao corpo. Empurre a corda para baixo abrindo as pontas no final e volte devagar.'),
(null, 'Tríceps testa', 'strength', 'reps_load', 'triceps', '{}', 'barra', false,
 'Deitado, braços para cima. Desça a barra em direção à testa dobrando só os cotovelos e estenda de volta.'),
(null, 'Tríceps francês com halter', 'strength', 'reps_load', 'triceps', '{}', 'halteres', false,
 'Sentado, halter atrás da cabeça segurado com as duas mãos. Estenda os braços para cima e desça devagar.'),
(null, 'Mergulho no banco', 'strength', 'reps_only', 'triceps', '{chest,delts}', 'banco', false,
 'Mãos no banco atrás do corpo. Desça dobrando os cotovelos até 90° e empurre de volta.'),
(null, 'Rosca de punho', 'strength', 'reps_load', 'forearms', '{}', 'barra', false,
 'Antebraços apoiados nas coxas, palmas para cima. Suba a barra dobrando só os punhos e desça.'),
-- Pernas
(null, 'Agachamento livre com barra', 'strength', 'reps_load', 'quads', '{glutes,hamstrings,lowerback}', 'barra', false,
 'Barra apoiada nas costas, pés na largura dos ombros. Desça como se fosse sentar mantendo o peito alto e suba empurrando o chão.'),
(null, 'Agachamento no Smith', 'strength', 'reps_load', 'quads', '{glutes}', 'Smith', false,
 'Pés um pouco à frente da barra. Desça até as coxas ficarem paralelas ao chão e suba.'),
(null, 'Agachamento goblet', 'strength', 'reps_load', 'quads', '{glutes,abs}', 'halteres', false,
 'Halter junto ao peito. Desça com o tronco alto e os joelhos abrindo na direção dos pés e suba.'),
(null, 'Leg press 45°', 'strength', 'reps_load', 'quads', '{glutes,hamstrings}', 'máquina', false,
 'Pés na largura dos ombros na plataforma. Desça até os joelhos chegarem a 90° sem tirar o quadril do banco e empurre de volta.'),
(null, 'Cadeira extensora', 'strength', 'reps_load', 'quads', '{}', 'máquina', false,
 'Joelho alinhado ao eixo da máquina. Estenda as pernas, segure um instante e desça devagar.'),
(null, 'Afundo com halteres', 'strength', 'reps_load', 'quads', '{glutes,hamstrings}', 'halteres', true,
 'Um passo à frente. Desça até os dois joelhos chegarem a 90° e volte empurrando com a perna da frente.'),
(null, 'Agachamento búlgaro', 'strength', 'reps_load', 'quads', '{glutes}', 'halteres', true,
 'Pé de trás apoiado no banco. Desça até a coxa da frente ficar paralela ao chão e suba.'),
(null, 'Passada andando', 'strength', 'reps_load', 'quads', '{glutes,hamstrings}', 'halteres', true,
 'Dê passos largos à frente descendo o joelho de trás perto do chão a cada passo.'),
(null, 'Mesa flexora', 'strength', 'reps_load', 'hamstrings', '{calves}', 'máquina', false,
 'Deitado de bruços, joelho alinhado ao eixo. Dobre as pernas trazendo o rolo ao glúteo e desça devagar.'),
(null, 'Cadeira flexora', 'strength', 'reps_load', 'hamstrings', '{}', 'máquina', false,
 'Sentado, rolo atrás dos tornozelos. Dobre os joelhos puxando o rolo para baixo e volte devagar.'),
(null, 'Stiff com barra', 'strength', 'reps_load', 'hamstrings', '{glutes,lowerback}', 'barra', false,
 'Joelhos levemente dobrados. Desça a barra rente às pernas levando o quadril para trás e suba contraindo glúteos.'),
(null, 'Elevação pélvica com barra', 'strength', 'reps_load', 'glutes', '{hamstrings}', 'barra', false,
 'Costas apoiadas no banco, barra no quadril. Suba o quadril até alinhar com o tronco, segure e desça.'),
(null, 'Glúteo na polia (coice)', 'strength', 'reps_load', 'glutes', '{hamstrings}', 'polia', true,
 'Tornozeleira na polia baixa. Leve a perna para trás estendendo o quadril e volte devagar.'),
(null, 'Cadeira abdutora', 'strength', 'reps_load', 'abductors', '{glutes}', 'máquina', false,
 'Sentado, costas apoiadas. Abra as pernas contra a resistência e feche devagar.'),
(null, 'Cadeira adutora', 'strength', 'reps_load', 'adductors', '{}', 'máquina', false,
 'Sentado, costas apoiadas. Feche as pernas contra a resistência e abra devagar.'),
(null, 'Panturrilha em pé', 'strength', 'reps_load', 'calves', '{}', 'máquina', false,
 'Ponta dos pés na plataforma. Suba o máximo que puder, segure um instante e desça até alongar.'),
(null, 'Panturrilha sentado', 'strength', 'reps_load', 'calves', '{}', 'máquina', false,
 'Joelhos sob o apoio. Suba os calcanhares o máximo possível e desça devagar.'),
-- Abdômen e core
(null, 'Prancha', 'complementary', 'time', 'abs', '{lowerback,delts}', 'peso do corpo', false,
 'Antebraços no chão, corpo reto da cabeça aos pés. Contraia o abdômen e segure sem deixar o quadril cair.'),
(null, 'Prancha lateral', 'complementary', 'time', 'abs', '{abductors}', 'peso do corpo', true,
 'Apoiado em um antebraço, corpo de lado e reto. Segure o quadril alto.'),
(null, 'Abdominal supra', 'strength', 'reps_only', 'abs', '{}', 'peso do corpo', false,
 'Deitado, joelhos dobrados. Tire os ombros do chão contraindo o abdômen e desça devagar.'),
(null, 'Abdominal infra', 'strength', 'reps_only', 'abs', '{}', 'peso do corpo', false,
 'Deitado, pernas para cima. Tire o quadril do chão levando os joelhos ao peito e desça controlando.'),
(null, 'Abdominal na polia', 'strength', 'reps_load', 'abs', '{}', 'polia', false,
 'Ajoelhado, corda atrás da cabeça. Flexione o tronco levando os cotovelos aos joelhos e volte.'),
(null, 'Elevação de pernas na barra', 'strength', 'reps_only', 'abs', '{forearms}', 'barra fixa', false,
 'Pendurado. Eleve as pernas até a linha do quadril ou mais sem balançar e desça devagar.'),
-- Cardio e condicionamento
(null, 'Esteira', 'cardio', 'distance_time', null, '{}', 'esteira', false,
 'Caminhe ou corra no ritmo combinado. Ajuste a inclinação conforme o treino.'),
(null, 'Bicicleta ergométrica', 'cardio', 'time', 'quads', '{calves}', 'bicicleta', false,
 'Ajuste o banco para a perna quase estender embaixo. Pedale no ritmo combinado.'),
(null, 'Elíptico', 'cardio', 'time', null, '{}', 'elíptico', false,
 'Postura alta, use braços e pernas juntos no ritmo combinado.'),
(null, 'Remo ergômetro', 'cardio', 'distance_time', 'lats', '{quads,hamstrings}', 'remo', false,
 'Empurre com as pernas, depois puxe com os braços até o abdômen; volte na ordem inversa.'),
(null, 'Pular corda', 'conditioning', 'time', 'calves', '{}', 'corda', false,
 'Saltos baixos na ponta dos pés, girando a corda com os punhos.'),
(null, 'Burpee', 'conditioning', 'reps_only', 'quads', '{chest,abs}', 'peso do corpo', false,
 'Agache, leve as pernas para trás em prancha, volte e salte com os braços para cima.'),
(null, 'Polichinelo', 'conditioning', 'time', 'calves', '{delts}', 'peso do corpo', false,
 'Salte abrindo pernas e braços ao mesmo tempo e volte fechando.'),
(null, 'Kettlebell swing', 'conditioning', 'reps_load', 'glutes', '{hamstrings,lowerback,delts}', 'kettlebell', false,
 'Leve o kettlebell entre as pernas levando o quadril para trás e projete à frente estendendo o quadril com força.'),
(null, 'Mountain climber', 'conditioning', 'time', 'abs', '{quads,delts}', 'peso do corpo', false,
 'Em prancha alta, traga os joelhos ao peito alternando rápido sem levantar o quadril.');
