// Textos da anamnese e das restrições (pt-BR), num lugar só e prontos para i18n.
import type { Clearance, RestrictionKind, Section } from "../domain/anamnesis";

export const strings = {
  sections: {
    goal: { title: "Seu\nobjetivo", hint: "Para o personal montar o treino certo para você." },
    routine: { title: "Sua\nrotina", hint: "Quanto tempo você tem para treinar." },
    parq: {
      title: "Sua\nsaúde",
      hint: "Perguntas rápidas de segurança antes de começar. Responda com sinceridade.",
    },
    health: {
      title: "Dores e\nhistórico",
      hint: "Tudo opcional. Só o seu personal vê, e fica guardado com criptografia.",
    },
  } satisfies Record<Section, { title: string; hint: string }>,
  form: {
    yes: "Sim",
    no: "Não",
    less: "Menos",
    more: "Mais",
    step: (n: number, total: number) => `Passo ${String(n)} de ${String(total)}`,
    next: "Continuar",
    back: "Voltar",
    later: "Terminar depois",
    send: "Enviar anamnese",
    missing: "Responda as perguntas obrigatórias para continuar.",
    parqWarning:
      "Por uma das respostas, o recomendado é ter liberação médica antes de começar. Seu personal é avisado e combina com você.",
    sent: "Anamnese enviada",
    sentText: "Seu personal recebe agora para revisar. Dá para atualizar depois em Perfil.",
    done: "Pronto",
  },
  banner: {
    title: "Complete sua anamnese",
    text: "Leva uns 3 minutos e deixa seu treino mais seguro.",
    draft: "Você começou e não terminou. Continue de onde parou.",
    action: "Preencher agora",
    resume: "Continuar",
  },
  review: {
    title: "Anamnese",
    back: "Voltar",
    empty: "Ainda não respondida",
    emptyText:
      "O aluno preenche no app depois de aceitar o convite. Assim que enviar, aparece aqui.",
    version: (n: number) => `Versão ${String(n)}`,
    reviewed: (date: string) => `Revisada em ${date}`,
    toReview: "Aguardando sua revisão",
    parq: 'PAR-Q com "sim": liberação médica recomendada',
    clearance: "Liberação médica",
    clearanceDate: "Data do atestado (AAAA-MM-DD)",
    clearanceOptions: {
      not_required: "Não precisa",
      pending: "Pendente",
      cleared: "Liberado",
    } satisfies Record<Clearance, string>,
    edit: "Complementar respostas",
    stopEdit: "Ver respostas",
    save: "Revisar e travar",
    saveNew: "Salvar nova versão",
    lockedHint: "Depois de revisada, a versão fica travada; mudanças viram uma versão nova.",
    saved: "Revisão salva.",
    versions: "Versões",
    unanswered: "—",
  },
  restrictions: {
    title: "Restrições",
    add: "Adicionar restrição",
    empty: "Nenhuma restrição ativa.",
    resolved: "Resolvidas",
    edit: "Editar",
    kind: "Tipo",
    kinds: {
      injury: "Lesão",
      surgery: "Cirurgia",
      pain: "Dor",
      condition: "Condição",
    } satisfies Record<RestrictionKind, string>,
    region: "Região do corpo",
    noRegion: "Sem região",
    description: "Descrição",
    severity: "Gravidade",
    severities: ["Leve", "Moderada", "Grave"] as const,
    resolvedToggle: "Já resolvida",
    save: "Salvar restrição",
    remove: "Excluir",
    removeTitle: "Excluir esta restrição?",
    removeText: "Use só para o que foi lançado errado. Para o que melhorou, marque como resolvida.",
    cancel: "Cancelar",
    sheetNew: "Nova restrição",
    sheetEdit: "Editar restrição",
    banner: (n: number) => (n === 1 ? "1 restrição ativa" : `${String(n)} restrições ativas`),
    open: "Anamnese e restrições",
    warning: "Atenção:",
  },
  regions: {
    neck: "Pescoço",
    shoulder_left: "Ombro esq.",
    shoulder_right: "Ombro dir.",
    elbow_left: "Cotovelo esq.",
    elbow_right: "Cotovelo dir.",
    wrist_left: "Punho esq.",
    wrist_right: "Punho dir.",
    chest: "Peito",
    upper_back: "Costas",
    lower_back: "Lombar",
    hip_left: "Quadril esq.",
    hip_right: "Quadril dir.",
    knee_left: "Joelho esq.",
    knee_right: "Joelho dir.",
    ankle_left: "Tornozelo esq.",
    ankle_right: "Tornozelo dir.",
    other: "Outro lugar",
  } as Readonly<Record<string, string>>,
} as const;
