import type { BlockMethod, SetType } from "../domain/workout";

// Textos da feature training (pt-BR), num lugar só e prontos para i18n.
export const strings = {
  templates: {
    title: "Treinos",
    subtitle: "Seus modelos para montar os treinos dos alunos.",
    create: "Novo modelo",
    newName: "Novo treino",
    library: "Biblioteca de exercícios",
    librarySubtitle: "Busque, veja como fazer e cadastre os seus",
    emptyTitle: "Monte seu primeiro modelo",
    emptyText:
      "Um modelo vira o treino de qualquer aluno com um toque. Comece pelo que você mais passa.",
    meta: (exercises: number, minutes: number | null) =>
      [
        exercises === 1 ? "1 exercício" : `${String(exercises)} exercícios`,
        minutes === null ? null : `~${String(minutes)} min`,
      ]
        .filter((part) => part !== null)
        .join(" · "),
    error: "Não conseguimos carregar seus modelos.",
    retry: "Tentar de novo",
  },
  editor: {
    back: "Voltar",
    name: "Nome do treino",
    goal: "Foco (opcional)",
    goalPlaceholder: "Peito e tríceps",
    minutes: "Tempo estimado (min)",
    unsaved: "Alterações não salvas",
    saved: "Salvo",
    save: "Salvar",
    addBlock: "Adicionar bloco",
    addExercise: "Adicionar exercício",
    block: (n: number) => `Bloco ${String(n)}`,
    moveUp: "Subir",
    moveDown: "Descer",
    remove: "Remover",
    editSets: "Editar séries",
    totals: (exercises: number, sets: number) =>
      `${exercises === 1 ? "1 exercício" : `${String(exercises)} exercícios`} · ${
        sets === 1 ? "1 série" : `${String(sets)} séries`
      }`,
    emptyTitle: "Adicione o primeiro bloco",
    emptyText: "Um bloco junta exercícios num jeito de treinar: um por vez, biset, circuito…",
    rounds: "Rodadas",
    work: "Esforço (s)",
    rest: "Descanso (s)",
    restRounds: "Descanso entre rodadas (s)",
    duration: "Duração (min)",
    discardTitle: "Sair sem salvar?",
    discardMessage: "As alterações deste treino vão se perder.",
    discardStay: "Continuar editando",
    discardLeave: "Sair",
    offline: "Sem internet. O rascunho continua aqui; toque em Salvar quando a conexão voltar.",
    problems: {
      name: "Dê um nome ao treino.",
      "block-empty": "Tem bloco sem exercício.",
      "superset-needs-two": "Biset precisa de pelo menos dois exercícios.",
      "circuit-needs-two": "Circuito precisa de pelo menos dois exercícios.",
      "sets-required": "Todo exercício precisa de séries.",
      "reps-invalid": "O mínimo de repetições passou do máximo.",
    },
    error: "Não conseguimos abrir o treino.",
    retry: "Tentar de novo",
    version: (n: number) => `versão ${String(n)}`,
  },
  methods: {
    sequential: { label: "Um por vez", hint: "Séries de um exercício, depois o próximo" },
    superset: { label: "Biset / triset", hint: "Exercícios em sequência, sem descanso entre eles" },
    circuit: { label: "Circuito", hint: "Rodadas passando por todos os exercícios" },
    hiit: { label: "Tabata", hint: "8 rodadas de 20 s de esforço e 10 s de descanso" },
    intervals: { label: "Intervalado", hint: "Esforço e descanso por tempo, em rodadas" },
    emom: { label: "EMOM", hint: "A cada minuto, no minuto, até o fim do tempo" },
    amrap: { label: "AMRAP", hint: "Máximo de rodadas no tempo" },
  } satisfies Record<BlockMethod, { label: string; hint: string }>,
  pickMethod: { title: "Novo\nbloco", subtitle: "Como os exercícios deste bloco são feitos?" },
  sets: {
    title: "Séries",
    number: "#",
    type: "Tipo",
    reps: "Reps",
    repsMax: "até",
    kg: "kg",
    time: "Tempo (s)",
    distance: "Distância (m)",
    rest: "Desc. (s)",
    rir: "Reps sobrando (RIR)",
    rirHint: "Esforço alvo: parar com N repetições sobrando",
    add: "Adicionar série",
    applyAll: "Aplicar a primeira a todas",
    removeSet: (n: number) => `Remover série ${String(n)}`,
    done: "Pronto",
    notes: "Orientação para o aluno (opcional)",
    types: {
      warmup: "Aquec.",
      normal: "Normal",
      drop: "Drop",
      rest_pause: "Rest-pause",
      failure: "Falha",
    } satisfies Record<SetType, string>,
  },
  conflict: {
    title: "Alterado em\noutro celular",
    text: "Enquanto você editava, este treino foi salvo em outro aparelho. Nada foi perdido: escolha qual versão fica.",
    useSaved: "Usar a versão salva",
    useMine: "Substituir pela minha versão",
  },
  program: {
    noneTitle: "Sem programa ainda",
    noneText: "Crie o programa com o objetivo e a agenda; depois adicione os treinos A, B, C…",
    create: "Criar programa",
    newTitle: "Novo\nprograma",
    name: "Nome do programa",
    namePlaceholder: "Hipertrofia",
    goal: "Objetivo (opcional)",
    startsOn: "Início (DD/MM/AAAA, opcional)",
    endsOn: "Fim (DD/MM/AAAA, opcional)",
    dateInvalid: "Use o formato DD/MM/AAAA.",
    mode: "Agenda",
    modes: { fixed_days: "Dias fixos", sequence: "Sequência" },
    modeHint: {
      fixed_days: "Treino A na segunda e quinta, B na terça e sexta…",
      sequence: "A → B → C na ordem, com uma meta de treinos por semana",
    },
    weeklyTarget: "Treinos por semana",
    week: (current: number, total: number) => `Semana ${String(current)} de ${String(total)}`,
    perWeek: (n: number) => `${String(n)}x por semana`,
    addWorkout: "Novo treino",
    fromTemplate: "A partir de um modelo",
    blank: "Treino em branco",
    workoutName: (letter: string) => `Treino ${letter}`,
    noDays: "sem dia marcado",
    saveSchedule: "Salvar agenda",
    back: "Voltar",
    error: "Não conseguimos carregar o programa.",
    retry: "Tentar de novo",
    days: ["D", "S", "T", "Q", "Q", "S", "S"],
    dayNames: ["domingo", "segunda", "terça", "quarta", "quinta", "sexta", "sábado"],
    nameRequired: "Dê um nome ao programa.",
  },
} as const;
